on: [push, pull_request]

name: cover

jobs:
  cover:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: false
      NOT_CRAN: true

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::rstudioapi
          needs: coverage

      - name: Test coverage
        run: |
          out <- covr::zero_coverage(covr::package_coverage())
          out <- out[!grepl("^src", out$filename),, drop = FALSE]
          print(out)
          if (nrow(out)) stop("some lines not covered by tests")
        shell: Rscript {0}
